name: Python Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-22.04
            python-version: "3.6"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: python -m pip install --upgrade pip wheel build
      - name: Build
        run: python -m build
      - name: Install Locally
        run: pip install dist/sleep_until-*.tar.gz
      - name: Test
        run: python test.py
